### PR TITLE
Update Core.nuspec

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by MichaelKetting** [comment]
Hello Simon,
thank you for the pull request! Before I can accept it, we'll need a signed CLA, though, please see  https://github.com/re-motion/Relinq/wiki/Contributing for details.
~Michael

**Comment by SimonCropp** [comment]
@MichaelKetting sorry i dont have time to jump through hoops for such a trivial change. feel free to fix the link yourself. suggest you slightly change your policy to not need a CLA for trivial changes?

and keep up the good work on your project

**Comment by MichaelKetting** [comment]
@SimonCropp, yeah, sorry about the red tape. Was worried about that but the legalese isn't really up to me, personally, and setting up a more relaxed system is...well...a longer discussion with legal :/

I did put your request on the issue list, though: https://www.re-motion.org/jira/browse/RMLNQ-118 (as well as the cla suggestion)

**Comment by MichaelKetting** [comment]
@SimonCropp just to let you know, we've now had time to discuss CLA and copyright, and decided that changes such as yours are non-issues as far as CLA and copyright are conserned. There also happened to be a second PR (https://github.com/re-motion/Relinq/pull/12/) with the same change, so the new URL is now in the system.

**Pull request closed without merging**
